### ISSUE TITLE
Facebook Ads only shows when the testing is enabled.

### ISSUE THREAD

**Issue by eyeveye** [eduardoqc183/XamarinFormsFacebookAdsDemo#1]
When I turn on the testing in facebook, the Ads show (banner and interstitial ads). 

If I disable the testing in facebook, the ads will not show at all.

**Comment by eduardoqc183** [comment]
Try with an internal test in playstore.

**Comment by eyeveye** [comment]
> Try with an internal test in playstore.

What do you mean by internal test in playstore?
I do have my Admob running okie in the same app.

**Comment by eduardoqc183** [comment]
facebook only shows testing ads in testing devices, if you want to see real ads you must publish the app at the playstore.
But if you are using admob, you must implement bidding for facebook.
